name: PyPI publishing

on: push

jobs:
  pypi:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # build the calculate-liam package and store outputs in dist folder
      - run: pipx run build calculate-liam -o dist
      # check the files in dist are valid
      - run: pipx run twine check dist/*
      # if this commit is tagged, upload the release to (test)PyPI
      - if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
